# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xisGd-s3erd4jscTgCknyNUWXA92S4Q9
"""

# 1 -Write a program that counts up the number of vowels [a, e, i, o, u] contained in the string.

name = "mmmaeiou"
name.count('a' ) + name.count('e' ) + name.count('i' ) + name.count('o' )+name.count('u' )

# 2- Fill an array of 5 elements from the user, Sort it in descending 
#and ascending orders then display the output.

arr = []
for i in range(5):
  num = int(input("Enter the value num " + str(i+1)  + " : " ) )
  arr.append(num)
Array_asc = sorted(arr)
Array_desc = sorted(arr , reverse=True)
print(Array_asc)
print(Array_desc)

# 3- Write a program that prints the number of times the string 'iti' 
#occurs in anystring.

x = input('enter the name ')
x.count('iti')

# 4- Write a program that remove all vowels from the input word and generate a brief version of it.


vowles = "aeiouAEIOU"
arr = [] 
for i in range(3):
  value = input("enter the value number " + str(i+1) + " : ")
  word_without_vowels = ""
  for i in value :
    if i not in vowles :
      word_without_vowels += char

  arr.append(value)
arr

# 5- Write a program that prints the locations of "i" character in any string you added.

string = "mahmouid"
string.find("i")

# 6 - Write a program that generate a multiplication table from 1 to the number passed

x = int(input("enter the number plz  ") ) 

for i in range(1,x+1):
  for j in range(13):
    result = i * j 
    print (" " , i , " * " , j ," = " , result)
  print("------------------------------------------------")

# 7-  Write a program that build a Mario pyramid like below
for i in range (5):
  print ((4-i)*" " + (i)*"*")

# 7 -Write a program that build a Mario pyramid like below
for i in range (5):
  x = 5
  print ((x-i)*" "+i*"*")